name: rl


defaults:
  - agent: ../../agent/td3
  - rl_env: ../../rl_env/inverted_pendulum
  - _self_

seed: 30


debug_mode: True
eval_mode: False


eval_interval: 1000
num_agents: 100

device: cuda:0


######## RL outer configuration ########
replay_buffer:
  _target_: agents.replay_memory.ReplayMemory
  capacity: 100000
  seed: ${seed}

batch_size: 32


save_root: "param_data"

train_layer: "all"

########################

data:
  data_root: data/rl
  dataset: Null
  batch_size: 200
  num_workers: 1


param:
  data_root: param_data/Pendulum-v1_current_policy/data.pt
  val_data_root: param_data/Pendulum-v1_current_policy/val_data.pt
  k: 10000
  num_workers: 4
  batch_size: 128


load_system_checkpoint: