name: ddpm

model:
  arch:
    _target_: core.module.wrapper.ema.EMA
    model:
      _target_: core.module.modules.unet.AE_CNN_bottleneck
      in_channel: 1
      in_dim: 3715

#     model:
#       _target_: core.module.modules.od_unet.AE_CNN_bottleneck
#       in_dim: 52

#data_transform:
#  system_cls: core.system.encoder.EncoderSystem
#  checkpoint_path: ${output_dir}/encoder/checkpoints/last.ckpt

beta_schedule:
  start: 1e-4
  end: 2e-2
  schedule: linear
  n_timestep: 1000

model_mean_type: eps
model_var_type: fixedlarge
loss_type: mse

train:
  optimizer:
    _target_: torch.optim.AdamW
    lr: 1e-3
    weight_decay: 2e-6

  lr_scheduler:

  trainer:
    _target_: pytorch_lightning.Trainer
    _convert_: all
    max_epochs: 10000
    check_val_every_n_epoch: 500
    val_check_interval : 500
    log_every_n_steps: 10
    limit_val_batches: 1
    limit_test_batches: 1
    devices:
      - ${device.id}

    enable_model_summary: false

    callbacks:
      - _target_: pytorch_lightning.callbacks.ModelCheckpoint
        monitor: 'best_g_acc'
        mode: 'max'
        save_top_k: 3
        save_last: true
        filename: 'ddpm_{epoch}-{best_g_acc:.4f}'


    logger:
      _target_: pytorch_lightning.loggers.TensorBoardLogger
      save_dir: ${output_dir}/${system.name}/
      name: 'tensorboard'

