name: rl


defaults:
  - agent: ../../agent/td3
  - rl_env: ../../rl_env/inverted_pendulum
  - _self_

seed: 30


debug_mode: True
eval_mode: False


eval_interval: 1000
num_agents: 200

device:
  cuda_visible_devices:  "0,1,2,3,4,5,6"
  id: 0
  cuda: cuda:${device.id}


######## RL outer configuration ########
replay_buffer:
  _target_: core.utils.replay_memory.ReplayMemory
  capacity: 100000
  seed: ${seed}

batch_size: 256

max_steps: ???

save_root: "param_data"

train_layer: "all"

########################

data:
  data_root: data/rl
  dataset: ???
  batch_size: 64
  num_workers: 1