defaults:
  - task: rl
  - system: autoencoder
  - _self_



seed: 30

device:
  cuda_visible_devices:  "0,1,2,3,4,5,6"
  id: 0
  cuda: cuda:0


#######################################
mode: train

process_title: Diffusion Upscale

output_dir: outputs/rl

hydra:
  output_subdir: config
  run:
    dir: ${output_dir}
  sweep:
    dir: ${output_dir}
    subdir: ${hydra.job.override_dirname}