defaults:
  - task: rl
  - system: autoencoder
  - _self_



seed: 30


#######################################
load_system_checkpoint:
mode: train

process_title: p-diff

output_dir: outputs/rl

hydra:
  output_subdir: config
  run:
    dir: ${output_dir}
  sweep:
    dir: ${output_dir}
    subdir: ${hydra.job.override_dirname}