defaults:
  - task: rl
  - system: autoencoder
  - agent: td3
  - rl_env: inverted_pendulum
  - _self_



seed: 30
debug_mode: False
eval_mode: False


eval_interval: 1000
num_agents: 200

device:
  cuda_visible_devices:  "0,1,2,3,4,5,6"
  id: 0
  cuda: cuda:${device.id}


######## RL outer configuration ########
replay_buffer:
  _target_: core.utils.replay_memory.ReplayMemory
  capacity: 100000
  seed: ${global_seed}

batch_size: 256







#######################################
load_system_checkpoint:
mode: train

process_title: p-diff

output_dir: outputs/cifar100

hydra:
  output_subdir: config
  run:
    dir: ${output_dir}
  sweep:
    dir: ${output_dir}
    subdir: ${hydra.job.override_dirname}