agent_name: td3

agent:
  _target_: agents.td3.TD3Agent
  obs_shape: ??? # to be specified later
  act_shape: ??? # to be specified later
  act_limit_low: ???
  act_limit_high: ???
  device: cuda:${device.id}
  lr: 1e-3
  hidden_dim: 256
  critic_target_tau: 0.01
  num_expl_steps: 1000
  update_every_steps: 2
  stddev_schedule: 'linear(0.2,0.1,1000)'
  stddev_clip: 0.15
  discount: 0.98
