agent_name: td3

agent:
  _target_: agents.td3.TD3Agent
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  device: cuda:${device.id}
  lr: 1e-4
  critic_target_tau: 0.01
  update_every_steps: 2
  num_expl_steps: 2000
  hidden_dim: 256
  stddev_schedule: 'linear(1.0,0.1,100000)'
  stddev_clip: 0.3
  discount: 0.99
