agent_name: td3

agent:
  _target_: agents.td3.TD3Agent
  obs_shape: 3
  act_shape: 1
  act_limit_low: -2
  act_limit_high: 2
  device: "cuda:0"
  lr: 1e-3
  hidden_dim: 32
  critic_target_tau: 0.01
  num_expl_steps: 0
  update_every_steps: 2
  stddev_schedule: 'linear(0.5,0.05,5000)'
  stddev_clip: 0.3
  discount: 0.99
