agent_name: td3

agent:
  _target_: agents.td3.TD3Agent
  obs_shape: ${rl_env.obs_shape}
  act_shape: ${rl_env.act_shape}
  act_limit_low: ${rl_env.act_limit_low}
  act_limit_high: ${rl_env.act_limit_high}
  device: ${device}
  lr: 1e-3
  hidden_dim: 32
  critic_target_tau: 0.01
  num_expl_steps: 0
  update_every_steps: 2
  stddev_schedule: 'linear(0.5,0.05,5000)'
  stddev_clip: 0.3
  discount: 0.99
