agent_name: td3

agent:
  _target_: agents.td3.TD3Agent
  obs_shape: ??? # to be specified later
  act_shape: ??? # to be specified later
  act_limit_low: ???
  act_limit_high: ???
  device: cuda:${device.id}
  lr: 3e-4
  hidden_dim: 256
  critic_target_tau: 0.01
  num_expl_steps: 2000
  update_every_steps: 2
  stddev_schedule: 'linear(0.5,0.05,5000)'
  stddev_clip: 0.3
  discount: 0.99
